version: "3.8"

services: 
 db:
    image: mysql:latest
    volumes:
      - ./db/data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: sys
    ports:
      - 49180:3306
  
 web:
    depends_on:
      - db
    image: tomcat:9
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: sys
    ports:
      - '10000:8080'
